harbor:
  expose:
    tls:
      certSource: secret
      secret:
        secretName: harbor-tls
    ingress:
      hosts:
        core: harbor.10.7.2.72.nip.io
      annotations:
        cert-manager.io/cluster-issuer: ca-cluster-issuer
  trivy:
    enabled: false
  chartmuseum:
    enabled: false
  notary:
    enabled: false
  metrics:
    enabled: false
  externalURL: https://harbor.10.7.2.72.nip.io