apiVersion: v2
name: harbor
description: A Helm chart for Harbor
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: harbor/harbor
  version: 1.14.2
  repository: https://helm.goharbor.io/
